name: 'Airflow_dbt'
version: '1.0.0'
config-version: 2


profile: 'default'

model-paths: ["models"]

target-path: "target"
clean-targets: 
  - "target"
  - "dbt_packages"
models: 
  Airflow-Demo
    example:
      materialized: view