name: 'Airflow_dbt'
version: '1.0.0'
config-version: 2


profile: 'default'

model-paths: ["models"]
analyses-path: ["analyses"]
test-path: ["tests"]



target-path: "target"
clean-targets: 
  - "target"
  - "dbt_packages"
models: 
  Airflow-Demo:
      +materialized: view